### ISSUE TITLE
data sets

### ISSUE THREAD

**Issue by nadalno1** [caoxiaoyi03/RJMCMC#2]
hi ,I wonder why the Realdata txt is so small? where are the data sets?

**Comment by caoxiaoyi03** [comment]
The file Realdata.txt is the dataset. The program is designed to process datasets from single-cell measurements at the beginning (for example, Flowcell measurements), so the scale of the data is not extremely large.

**Comment by caoxiaoyi03** [comment]
There are several simulation datasets we used in the publication, Realdata.txt and Realdata0315.txt are examples, the latter is more close to the actual usage case.
